"""
training/train_swin.py
=======================
Swin Transformer Training Pipeline for BrailleVision 2026
==========================================================
TRAINING STRATEGY:
  Phase 1 (Epochs 1-5):   Freeze Swin stages, train head only (warm-up)
  Phase 2 (Epochs 6-30):  Unfreeze all, train end-to-end with low LR

TECHNIQUES USED:
  • Cosine LR schedule with warm-up
  • Label smoothing (handles ambiguous dot patterns)
  • Mixup augmentation (improves generalisation)
  • Gradient clipping (stable training)
  • Mixed precision (FP16) for speed
  • Early stopping (prevent overfitting on synthetic data)

Vibe-Coding Disclosure: Training pipeline designed with Claude (Anthropic).
"""
import sys, os
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
import os
import time
import json
import torch
import torch.nn as nn
import torch.optim as optim
from torch.cuda.amp import GradScaler, autocast
from torch.utils.data import DataLoader, Dataset
from torchvision import transforms
from pathlib import Path
from PIL import Image
import numpy as np
from typing import Optional

from model.swin_braille import build_model, ALL_CLASSES, CLASS_TO_IDX, NUM_CLASSES


# ---------------------------------------------------------------------------
# Dataset
# ---------------------------------------------------------------------------

class BrailleDataset(Dataset):
    """
    Loads per-class crops from data/classes/<char>/ directories.
    Generated by dataset_generator/generate.py
    """

    def __init__(
        self,
        root:      str,
        split:     str = 'train',
        transform = None,
    ):
        self.root      = Path(root)
        self.transform = transform
        self.samples   = []

        classes_dir = self.root / 'classes'
        if not classes_dir.exists():
            raise FileNotFoundError(
                f"Classes directory not found: {classes_dir}\n"
                "Run: python dataset_generator/generate.py first"
            )

        for cls_name in sorted(classes_dir.iterdir()):
            char = ' ' if cls_name.name == 'space' else cls_name.name
            if char not in CLASS_TO_IDX:
                continue
            label = CLASS_TO_IDX[char]
            imgs  = list(cls_name.glob('*.jpg'))

            # Split by filename hash for reproducibility
            total = len(imgs)
            if split == 'train':
                imgs = imgs[:int(total * 0.80)]
            elif split == 'val':
                imgs = imgs[int(total * 0.80):int(total * 0.90)]
            else:  # test
                imgs = imgs[int(total * 0.90):]

            for img_path in imgs:
                self.samples.append((img_path, label))

        print(f"[Dataset] {split}: {len(self.samples)} samples across {NUM_CLASSES} classes")

    def __len__(self):
        return len(self.samples)

    def __getitem__(self, idx):
        img_path, label = self.samples[idx]
        img = Image.open(img_path).convert('RGB')
        if self.transform:
            img = self.transform(img)
        return img, label


# ---------------------------------------------------------------------------
# Transforms
# ---------------------------------------------------------------------------

def get_transforms(split: str):
    """Returns augmentation pipeline for train/val/test."""

    # Swin-Tiny expects 96×96 (or 224×224)
    # We use 96×96 since Braille cells are small — less upscaling distortion
    IMG_SIZE = 96

    if split == 'train':
        return transforms.Compose([
            transforms.Resize((IMG_SIZE + 12, IMG_SIZE + 12)),
            transforms.RandomCrop(IMG_SIZE),
            transforms.RandomHorizontalFlip(p=0.0),   # Braille is NOT mirror-symmetric
            transforms.RandomRotation(degrees=5),
            transforms.ColorJitter(brightness=0.3, contrast=0.3, saturation=0.1),
            transforms.GaussianBlur(kernel_size=3, sigma=(0.1, 1.5)),
            transforms.ToTensor(),
            transforms.Normalize(mean=[0.485, 0.456, 0.406],
                                 std=[0.229, 0.224, 0.225]),
            transforms.RandomErasing(p=0.1, scale=(0.02, 0.08)),
        ])
    else:
        return transforms.Compose([
            transforms.Resize((IMG_SIZE, IMG_SIZE)),
            transforms.ToTensor(),
            transforms.Normalize(mean=[0.485, 0.456, 0.406],
                                 std=[0.229, 0.224, 0.225]),
        ])


# ---------------------------------------------------------------------------
# Mixup augmentation
# ---------------------------------------------------------------------------

def mixup_data(x, y, alpha=0.2):
    """Apply Mixup augmentation to a batch."""
    if alpha > 0:
        lam = np.random.beta(alpha, alpha)
    else:
        lam = 1.0

    batch_size = x.size(0)
    index      = torch.randperm(batch_size, device=x.device)

    mixed_x  = lam * x + (1 - lam) * x[index]
    y_a, y_b = y, y[index]
    return mixed_x, y_a, y_b, lam


def mixup_criterion(criterion, pred, y_a, y_b, lam):
    return lam * criterion(pred, y_a) + (1 - lam) * criterion(pred, y_b)


# ---------------------------------------------------------------------------
# Training config
# ---------------------------------------------------------------------------

class TrainConfig:
    DATA_DIR       = "data"
    OUTPUT_DIR     = "checkpoints"
    DEVICE         = "auto"

    # Phase 1: head warmup
    WARMUP_EPOCHS  = 5
    WARMUP_LR      = 1e-3
    FREEZE_STAGES  = 2      # Freeze first 2 Swin stages during warmup

    # Phase 2: full fine-tune
    TOTAL_EPOCHS   = 30
    BASE_LR        = 3e-5
    MIN_LR         = 1e-7
    WEIGHT_DECAY   = 0.05

    BATCH_SIZE     = 32
    NUM_WORKERS    = 4
    PIN_MEMORY     = True

    # Regularisation
    LABEL_SMOOTHING = 0.1
    MIXUP_ALPHA     = 0.2
    GRAD_CLIP       = 1.0

    # Early stopping
    PATIENCE        = 8

    # Mixed precision
    AMP             = True


# ---------------------------------------------------------------------------
# Trainer
# ---------------------------------------------------------------------------

class SwinTrainer:

    def __init__(self, cfg: TrainConfig = TrainConfig()):
        self.cfg = cfg
        Path(cfg.OUTPUT_DIR).mkdir(exist_ok=True)

        # Device
        if cfg.DEVICE == 'auto':
            self.device = (
                'cuda' if torch.cuda.is_available()
                else 'mps' if torch.backends.mps.is_available()
                else 'cpu'
            )
        else:
            self.device = cfg.DEVICE

        print(f"[Trainer] Device: {self.device}")

        # Datasets
        self.train_ds = BrailleDataset(cfg.DATA_DIR, 'train', get_transforms('train'))
        self.val_ds   = BrailleDataset(cfg.DATA_DIR, 'val',   get_transforms('val'))

        self.train_loader = DataLoader(
            self.train_ds, batch_size=cfg.BATCH_SIZE, shuffle=True,
            num_workers=cfg.NUM_WORKERS, pin_memory=cfg.PIN_MEMORY,
        )
        self.val_loader = DataLoader(
            self.val_ds, batch_size=cfg.BATCH_SIZE * 2, shuffle=False,
            num_workers=cfg.NUM_WORKERS, pin_memory=cfg.PIN_MEMORY,
        )

        # Model — Phase 1: freeze stages for warmup
        self.model = build_model(
            pretrained=True,
            dropout=0.3,
            freeze_stages=cfg.FREEZE_STAGES,
            device=self.device,
        )

        # Loss with label smoothing
        self.criterion = nn.CrossEntropyLoss(label_smoothing=cfg.LABEL_SMOOTHING)

        # Phase 1 optimiser (head only)
        self.optimizer = optim.AdamW(
            filter(lambda p: p.requires_grad, self.model.parameters()),
            lr=cfg.WARMUP_LR, weight_decay=cfg.WEIGHT_DECAY,
        )

        # Mixed precision scaler
        self.scaler = GradScaler(enabled=cfg.AMP and self.device == 'cuda')

        # Tracking
        self.best_val_acc  = 0.0
        self.patience_left = cfg.PATIENCE
        self.history       = {'train_loss': [], 'train_acc': [], 'val_loss': [], 'val_acc': []}

    # ─────────────────────────────────────────────────────────────────────
    # Main training loop
    # ─────────────────────────────────────────────────────────────────────

    def train(self):
        cfg = self.cfg
        print(f"\n{'='*60}")
        print(f"BrailleVision 2026 — Swin Transformer Training")
        print(f"{'='*60}")
        print(f"Total epochs  : {cfg.TOTAL_EPOCHS}")
        print(f"Warmup epochs : {cfg.WARMUP_EPOCHS}")
        print(f"Batch size    : {cfg.BATCH_SIZE}")
        print(f"Train samples : {len(self.train_ds)}")
        print(f"Val samples   : {len(self.val_ds)}")
        print(f"{'='*60}\n")

        for epoch in range(1, cfg.TOTAL_EPOCHS + 1):

            # ── Phase transition: unfreeze at end of warmup ────────────────
            if epoch == cfg.WARMUP_EPOCHS + 1:
                print("\n🔓 Warmup complete — unfreezing all Swin stages")
                for param in self.model.parameters():
                    param.requires_grad = True

                # Switch to lower LR for full fine-tuning
                self.optimizer = optim.AdamW(
                    self.model.parameters(),
                    lr=cfg.BASE_LR,
                    weight_decay=cfg.WEIGHT_DECAY,
                )
                self.scheduler = optim.lr_scheduler.CosineAnnealingLR(
                    self.optimizer,
                    T_max=cfg.TOTAL_EPOCHS - cfg.WARMUP_EPOCHS,
                    eta_min=cfg.MIN_LR,
                )

            # ── Train one epoch ────────────────────────────────────────────
            train_loss, train_acc = self._train_epoch(epoch)

            # ── Validate ───────────────────────────────────────────────────
            val_loss, val_acc = self._val_epoch()

            # ── LR step (only after warmup) ────────────────────────────────
            if epoch > cfg.WARMUP_EPOCHS and hasattr(self, 'scheduler'):
                self.scheduler.step()

            current_lr = self.optimizer.param_groups[0]['lr']

            # ── Log ────────────────────────────────────────────────────────
            print(
                f"Epoch {epoch:3d}/{cfg.TOTAL_EPOCHS} | "
                f"Train Loss: {train_loss:.4f} Acc: {train_acc:.2f}% | "
                f"Val Loss: {val_loss:.4f} Acc: {val_acc:.2f}% | "
                f"LR: {current_lr:.2e}"
            )

            self.history['train_loss'].append(train_loss)
            self.history['train_acc'].append(train_acc)
            self.history['val_loss'].append(val_loss)
            self.history['val_acc'].append(val_acc)

            # ── Save best checkpoint ───────────────────────────────────────
            if val_acc > self.best_val_acc:
                self.best_val_acc  = val_acc
                self.patience_left = cfg.PATIENCE
                self._save_checkpoint(epoch, val_acc, is_best=True)
                print(f"  ✅ New best val accuracy: {val_acc:.2f}%")
            else:
                self.patience_left -= 1
                if self.patience_left == 0:
                    print(f"\n⏹  Early stopping at epoch {epoch} (patience exhausted)")
                    break

        # ── Save training history ──────────────────────────────────────────
        with open(f"{cfg.OUTPUT_DIR}/history.json", 'w') as f:
            json.dump(self.history, f, indent=2)

        print(f"\n{'='*60}")
        print(f"Training complete!")
        print(f"Best val accuracy: {self.best_val_acc:.2f}%")
        print(f"Checkpoint saved:  {cfg.OUTPUT_DIR}/best_swin_braille.pth")
        print(f"{'='*60}")

    # ─────────────────────────────────────────────────────────────────────
    # Train epoch
    # ─────────────────────────────────────────────────────────────────────

    def _train_epoch(self, epoch: int):
        cfg = self.cfg
        self.model.train()
        total_loss = 0.0
        total_correct = 0
        total_samples = 0

        for batch_idx, (imgs, labels) in enumerate(self.train_loader):
            imgs   = imgs.to(self.device)
            labels = labels.to(self.device)

            # Mixup augmentation
            imgs, labels_a, labels_b, lam = mixup_data(imgs, labels, cfg.MIXUP_ALPHA)

            self.optimizer.zero_grad()

            with autocast(enabled=cfg.AMP and self.device == 'cuda'):
                logits = self.model(imgs)
                loss   = mixup_criterion(self.criterion, logits, labels_a, labels_b, lam)

            self.scaler.scale(loss).backward()
            self.scaler.unscale_(self.optimizer)
            torch.nn.utils.clip_grad_norm_(self.model.parameters(), cfg.GRAD_CLIP)
            self.scaler.step(self.optimizer)
            self.scaler.update()

            # Accuracy (on original labels_a for tracking)
            preds          = logits.argmax(dim=1)
            total_correct += (preds == labels_a).sum().item()
            total_samples += labels.size(0)
            total_loss    += loss.item()

        avg_loss = total_loss / len(self.train_loader)
        avg_acc  = 100.0 * total_correct / total_samples
        return avg_loss, avg_acc

    # ─────────────────────────────────────────────────────────────────────
    # Validation epoch
    # ─────────────────────────────────────────────────────────────────────

    def _val_epoch(self):
        cfg = self.cfg
        self.model.eval()
        total_loss    = 0.0
        total_correct = 0
        total_samples = 0

        with torch.no_grad():
            for imgs, labels in self.val_loader:
                imgs   = imgs.to(self.device)
                labels = labels.to(self.device)

                with autocast(enabled=cfg.AMP and self.device == 'cuda'):
                    logits = self.model(imgs)
                    loss   = self.criterion(logits, labels)

                preds          = logits.argmax(dim=1)
                total_correct += (preds == labels).sum().item()
                total_samples += labels.size(0)
                total_loss    += loss.item()

        avg_loss = total_loss / len(self.val_loader)
        avg_acc  = 100.0 * total_correct / total_samples
        return avg_loss, avg_acc

    # ─────────────────────────────────────────────────────────────────────
    # Save checkpoint
    # ─────────────────────────────────────────────────────────────────────

    def _save_checkpoint(self, epoch: int, val_acc: float, is_best: bool = False):
        cfg  = self.cfg
        ckpt = {
            'epoch':       epoch,
            'val_acc':     val_acc,
            'model_state': self.model.state_dict(),
            'optim_state': self.optimizer.state_dict(),
            'num_classes': NUM_CLASSES,
            'class_map':   {str(k): v for k, v in enumerate(ALL_CLASSES)},
        }
        name = 'best_swin_braille.pth' if is_best else f'epoch_{epoch}.pth'
        torch.save(ckpt, f"{cfg.OUTPUT_DIR}/{name}")


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    cfg     = TrainConfig()
    trainer = SwinTrainer(cfg)
    trainer.train()